export const sharedStyles = {
  container: {
    minHeight: '100vh',
    background: '#f9f7f4',
    fontFamily: 'sans-serif',
  },
  header: {
    background: '#D85A30',
    padding: '12px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#fff',
  },
  cafeName: { fontSize: 18, fontWeight: 700 },
  cafeNameEn: { fontSize: 12, opacity: 0.8 },
  langBtn: {
    background: 'rgba(255,255,255,0.2)',
    border: 'none', color: '#fff', padding: '5px 12px', borderRadius: 20,
    cursor: 'pointer', fontSize: 12,
  },
  homeLink: {
    background: 'rgba(255,255,255,0.2)',
    padding: '5px 12px', borderRadius: 20, color: '#fff',
    textDecoration: 'none', fontSize: 12,
  },
  tabs: {
    display: 'flex',
    gap: 0,
    background: '#fff',
    borderBottom: '1px solid #eee',
    padding: '0 16px',
  },
  tabBtn: {
    padding: '12px 20px',
    border: 'none',
    background: '#fff',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 500,
    borderBottom: '2px solid transparent',
  },
  content: {
    padding: 24,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    background: '#fff',
    borderRadius: 16,
    padding: 20,
    textAlign: 'center',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  statValue: {
    fontSize: 32,
    fontWeight: 700,
    color: '#D85A30',
  },
  statLabel: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  section: {
    background: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  formRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    alignItems: 'flex-end',
  },
  input: {
    padding: '8px 12px',
    border: '1px solid #ddd',
    borderRadius: 8,
    flex: 1,
    minWidth: 150,
  },
  select: {
    padding: '8px 12px',
    border: '1px solid #ddd',
    borderRadius: 8,
    background: '#fff',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 13,
  },
  primaryBtn: {
    background: '#D85A30',
    color: '#fff',
    border: 'none',
    padding: '8px 20px',
    borderRadius: 8,
    cursor: 'pointer',
    fontWeight: 600,
  },
  menuList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginTop: 16,
  },
  menuItemCard: {
    borderBottom: '1px solid #eee',
    padding: '8px 0',
  },
  menuItemRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  editForm: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  inputSmall: {
    padding: '6px 10px',
    border: '1px solid #ddd',
    borderRadius: 6,
    width: 120,
  },
  selectSmall: {
    padding: '6px 10px',
    border: '1px solid #ddd',
    borderRadius: 6,
  },
  toggleBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: 16,
    marginRight: 6,
  },
  editBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: 16,
    marginRight: 6,
  },
  deleteBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: 16,
    color: '#E24B4A',
  },
  saveBtn: {
    background: '#1D9E75',
    color: '#fff',
    border: 'none',
    padding: '4px 12px',
    borderRadius: 6,
    cursor: 'pointer',
  },
  cancelBtn: {
    background: '#ccc',
    border: 'none',
    padding: '4px 12px',
    borderRadius: 6,
    cursor: 'pointer',
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginTop: 16,
  },
  listItem: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr auto auto',
    gap: 12,
    padding: '8px 0',
    borderBottom: '1px solid #eee',
    alignItems: 'center',
    fontSize: 14,
  },
  quickActions: {
    display: 'flex',
    gap: 12,
    flexWrap: 'wrap',
  },
  quickBtn: {
    background: '#f0f0f0',
    border: 'none',
    padding: '8px 16px',
    borderRadius: 8,
    cursor: 'pointer',
  },
  reportButtons: {
    display: 'flex',
    gap: 12,
    marginTop: 16,
  },
  reportBtn: {
    background: '#f0f0f0',
    border: 'none',
    padding: '8px 16px',
    borderRadius: 8,
    cursor: 'pointer',
  },
}